### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by 2ndKeeper** [Insxnity/MonsterCatCss#1]
- #sr-header-area: text colour needs to be changed from white (and adjust user text and karma text colour on the top)

- Delete code for footer from Naut file (after we load 4.1 in)

- Fix custom text for subscribers and online users (missing a space between number and text) - can be fixed by uploading a new version of the CSS, it's already fixed in the GitHub files

- Remove spoiler flair and spoiler view, and customize built-in reddit spoiling instead

- Scrap current gold name system and replace with gold naming any approved submitters to the subreddit (https://www.reddit.com/r/csshelp/wiki/selectors).

- Formatting "mini sidebar" created when you hover over the tab

- Fixing some of the res buttons (i.e. the ones in the top right that show when you scroll past the header, the ones when you expand an image/gif)

**Comment by 2ndKeeper** [comment]
Oh, also fix the flair text showing up weirdly over the logo.

**Comment by 2ndKeeper** [comment]
Fix search bar messups:

Firefox + Windows 10 (without RES): https://i.imgur.com/edp5Cvc.png

Chrome + Windows 10 (with RES): https://i.imgur.com/i80NvbO.png

**Comment by 2ndKeeper** [comment]
Also fix whatever this is:

![sadyu](https://user-images.githubusercontent.com/32004299/30513502-5438d452-9ad2-11e7-8941-8ebef7bc99d7.PNG)

**Comment by Insxnity** [comment]
Everything but the sidebar has been fixed
