### ISSUE TITLE
To Do List #2

### ISSUE THREAD

**Issue by 2ndKeeper** [Insxnity/MonsterCatCss#10]
Whatever this is:

Non-RES:
![fsddgfi](https://user-images.githubusercontent.com/32004299/30526353-5043bd06-9be7-11e7-91b0-365a9ada70c1.PNG)

RES:
![dasfsdgdyfugkh](https://user-images.githubusercontent.com/32004299/30526393-b9efb412-9be7-11e7-8959-207eab3e6099.PNG)

Distinguishing without RES doesn't display properly. Also, bottom links on stickied comments aren't showing (with and without RES).

![addf](https://user-images.githubusercontent.com/32004299/30526357-6be18782-9be7-11e7-84d9-60b2c0775495.PNG)

Soulero flair needs to be fixed + Golden Monstercat Flair (class: mcat) needs to be added back.

Change tumblr social link button to be Instagram.

Spoiler icon is off again.
![assfg](https://user-images.githubusercontent.com/32004299/30526403-e527221e-9be7-11e7-90f9-3f06f163772b.PNG)

Disable spoiler flair.

Sidebar image link isn't working yet.

Album, EP, and LP have bugged out colours.

![sfdgdfhjk](https://user-images.githubusercontent.com/32004299/30527415-563489de-9bf6-11e7-8799-f17603d8bd49.PNG)

**Comment by Insxnity** [comment]
search fixed

**Comment by 2ndKeeper** [comment]
RES search bar still isn't fixed tho.

**Comment by 2ndKeeper** [comment]
.flairselector.drop-choices.active {
   z-index: 11;
}

.side .md blockquote:last-of-type p{
    top: 132px;
    right: 352px;
    position: absolute;
    z-index: 10;
}

**Comment by Insxnity** [comment]
res search appears to be fixed
flair selector fixed

**Comment by Insxnity** [comment]
comments fixed

**Comment by Insxnity** [comment]
Spoiler image fixed

**Comment by Insxnity** [comment]
Tumblr replaced

**Comment by Insxnity** [comment]
spoiler flair disabled

**Comment by Insxnity** [comment]
sidebar link added

**Comment by Insxnity** [comment]
Added default sticky color for automod posts
